# Generated by Django 4.2.1 on 2023-05-29 01:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sitioweb', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='producto',
            name='id',
        ),
        migrations.AddField(
            model_name='producto',
            name='sku',
            field=models.CharField(default='', max_length=50, primary_key=True, serialize=False),
        ),
    ]
