# Generated by Django 4.2.1 on 2023-06-01 03:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sitioweb', '0002_remove_producto_id_producto_sku'),
    ]

    operations = [
        migrations.AlterField(
            model_name='detallepedido',
            name='precio',
            field=models.SmallIntegerField(),
        ),
    ]
