# Generated by Django 4.2.1 on 2023-06-01 03:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sitioweb', '0004_alter_detallepedido_cantidad_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='detallepedido',
            name='cantidad',
            field=models.CharField(max_length=10),
        ),
    ]
