# Generated by Django 4.2.1 on 2023-06-01 03:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sitioweb', '0005_alter_detallepedido_cantidad'),
    ]

    operations = [
        migrations.AlterField(
            model_name='detallepedido',
            name='cantidad',
            field=models.PositiveSmallIntegerField(),
        ),
        migrations.AlterField(
            model_name='detallepedido',
            name='precio',
            field=models.PositiveBigIntegerField(),
        ),
    ]
