# Generated by Django 4.2.1 on 2023-06-01 03:59

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('sitioweb', '0007_alter_detallepedido_cantidad'),
    ]

    operations = [
        migrations.AlterField(
            model_name='detallepedido',
            name='producto',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='sitioweb.producto'),
        ),
    ]
