# Generated by Django 4.2.1 on 2023-06-01 04:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sitioweb', '0008_alter_detallepedido_producto'),
    ]

    operations = [
        migrations.AlterField(
            model_name='producto',
            name='sku',
            field=models.CharField(default='', max_length=50, primary_key=True, serialize=False, unique=True),
        ),
    ]
