# Generated by Django 4.2.1 on 2023-06-01 04:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('sitioweb', '0010_alter_producto_sku'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='detallepedido',
            name='producto',
        ),
    ]
