# Generated by Django 4.2.1 on 2023-06-01 04:32

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('sitioweb', '0011_remove_detallepedido_producto'),
    ]

    operations = [
        migrations.AddField(
            model_name='detallepedido',
            name='producto',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='sitioweb.producto'),
            preserve_default=False,
        ),
    ]
